#!/usr/bin/env bash
# Configures an Ubuntu server: localhost resolves to 127.0.0.1 and facebook.com resolves to 157.240.11.35
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.1 localhost/g' ~/hosts.new
sed -i '157 .240.11.35 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
